name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519_no_passphrase
        chmod 600 ~/.ssh/id_ed25519_no_passphrase
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: ssh -i ~/.ssh/id_ed25519_no_passphrase ${{ secrets.REMOTE_USER }}@${{ secrets.SERVER_IP }} "whoami && pwd"

    - name: Deploy via SSH
      run: |
        ssh -i ~/.ssh/id_ed25519_no_passphrase ${{ secrets.REMOTE_USER }}@${{ secrets.SERVER_IP }} "
          cd ~/app &&
          git pull origin main &&
          docker compose down &&
          docker compose up -d --build
        "